// src/localization/en.ts

import type { ILocalization } from './tr'

const resource: ILocalization = {
  hello: 'translated hello',
  name: 'Ali Burhan Keskin',
  confirm: 'Confirm',
  cancel: 'Cancel',
  generalActivityIndicatorText: 'Loading...',
  pleaseWait: 'Please wait... ',
  generalErrorText: 'An error occurred, please try again later.',
  search: 'Search',
  noInternet: 'No Internet Connection',
  yes: 'Yes',
  no: 'No',
  exit: 'Exit',
  brand: 'Brand',
  published: 'Published',
  min: 'min',
  piece: 'Piece',
  time: 'Time',
  description: 'Description',
  send: 'Send',
  next: 'Next',
  previous: 'Previous',
  retry: 'Retry',

  navigation: {
    home: 'Home Page',
    profile: 'Profile',
    settings: 'Settings',
    post: 'Post'
  },
  welcome: 'Welcome!',
  welcomeBack: 'Welcome back!',
  email: 'Email',
  password: 'Password',
  forgotPassword: 'Forgot password?',
  login: 'Login',
  or: 'or',
  loginWithGoogle: 'Login with Google',
  dontHaveAccount: "Don't have an account?",
  googleLoginNotImplemented: 'Google login is not yet implemented.',
  forgotPasswordNotImplemented:
    'Forgot password functionality is not yet implemented.',
  invalidCredentials: 'Invalid email or password',
  createAccount: 'Create Account',
  fullName: 'Full Name',
  firstName: 'First Name',
  lastName: 'Last Name',
  phone: 'Phone Number',
  invalidPhoneNumber: 'This is not a valid ivoirian phone number',
  invalidEmail: 'Invalid Email',
  confirmPassword: 'Confirm Password',
  passwordsDoNotMatch: 'Passwords do not match',
  acceptTerms: 'I accept the',
  termsAndConditions: 'Terms and Conditions',
  termsAndConditionsNotImplemented:
    'Terms and Conditions are not yet implemented.',
  registrationSuccessful: 'Registration successful!',
  back: 'Back',
  passwordStrength: {
    weak: 'Weak',
    fair: 'Fair',
    good: 'Good',
    strong: 'Strong',
    veryStrong: 'Very Strong'
  },
  title: 'Profile',
  theme: 'Theme',
  system: 'System',
  dark: 'Dark',
  light: 'Light',
  language: 'Language',
  fr: 'French',
  en: 'English',
  tr: 'Turkish',
  notifications: 'Notifications',
  logout: 'Logout',
  attendance: 'Attendance',
  notes: 'Grades',
  schedule: 'Schedule',
  exercises: 'Exercises',
  discussion: 'Discussion',
  infoAndSchooling: 'Info and Schooling',

  // Authentication & Profile
  googleLoginSuccess: 'Google login successful!',
  googleLoginFailed: 'Google login failed',
  signUp: 'Sign Up',
  signIn: 'Sign In',
  signInWithGoogle: 'Sign in with Google',
  signUpWithGoogle: 'Sign up with Google',
  alreadyHaveAccount: 'Already have an account?',
  completeProfile: 'Complete your profile',
  completeProfileSubtitle: 'Please provide some additional information.',
  profileIncomplete: 'Incomplete Profile',
  completeProfileToContinue: 'Please complete your profile to continue.',
  fillAllRequiredFields: 'Please fill in all required fields.',
  noUserLoggedIn: 'No user logged in.',
  profileUpdateError: 'An error occurred while updating the profile.',
  profileCompletedSuccessfully: 'Profile completed successfully!',
  finish: 'Finish',
  selectYourSchool: 'Select your school',
  phoneNumber: 'Phone Number',
  emailAddress: 'Email Address',
  joinYekoCommunity: 'Join the Yeko community and start managing your courses.',
  googleSignUpSuccess: 'Google sign up successful!',
  googleSignUpFailed: 'Google sign up failed',
  verifyYourEmail: 'Verify your email',
  confirmationEmailSent: 'A confirmation email has been sent to',
  clickLinkToActivate:
    'Please click the link in the email to activate your account.',
  backToLogin: 'Back to login',

  // Navigation & Tabs
  programs: 'Programs',
  schools: 'Schools',
  chats: 'Chats',
  profile: 'Profile',
  classNotes: 'Class Notes',

  // Schedule
  yourSchedule: 'Your Schedule',
  noClassScheduled: 'No class scheduled for this day',
  youAreStillWithoutSchool: 'You are still without a school establishment!',
  joinSchoolToStart:
    'To get started, please join at least one school establishment.',
  monday: 'Monday',
  tuesday: 'Tuesday',
  wednesday: 'Wednesday',
  thursday: 'Thursday',
  friday: 'Friday',
  mon: 'MON',
  tue: 'TUE',
  wed: 'WED',
  thu: 'THU',
  fri: 'FRI',

  // Chat
  discussions: 'Discussions',
  conversations: 'Conversations',
  unreadMessages: 'Unread Messages',
  all: 'All',
  unread: 'Unread',
  noUnreadMessages: 'No unread messages',
  noConversationsFound: 'No conversations found',
  messageLimitReached: 'Limit Reached',
  maxMessagesPerChat:
    'You have reached the maximum number of messages per chat (10 max).',
  goBack: 'Go back',
  sendMessage: 'Send message',
  noClass: 'No class',
  noSchool: 'No school',

  // Profile & Settings
  updateProfile: 'Update Profile',
  modifyNameAndPhoto: 'Modify your name and photo',
  joinNewSchool: 'Join a new school',
  enterOtpToLink: 'Enter the OTP code to link your profile to a new school',
  problemDuringLogout: 'A problem occurred during logout, please try again',
  willBeAvailableSoon: 'Will be available very soon',

  // Notes & Evaluation
  newEvaluation: 'New Evaluation',
  loading: 'Loading...',
  loadingSemesterData: 'Loading semester data...',
  semester: 'Semester',
  trimester: 'Trimester',
  subject: 'Subject',
  evaluationType: 'Evaluation Type',
  evaluationTitle: 'Evaluation Title',
  evaluationDescription: 'Evaluation Description',
  totalPoints: 'Total Points',
  coefficient: 'Coefficient',
  dueDate: 'Due Date',
  gradeEvaluation: 'Grade the evaluation',
  create: 'Create',
  creating: 'Creating...',
  titleRequired: 'Title is required',
  totalPointsMustBePositive: 'Total points must be a positive number',
  coefficientMustBePositive: 'Coefficient must be a positive number',
  subjectRequired: 'Subject is required',
  invalidSubject: 'Invalid subject',
  invalidSemester: 'Invalid semester',
  invalidDate: 'Invalid date',
  notTeacherOfThisClass: 'You are not a teacher of this class',
  noteNotFound: 'Note not found',
  errorSavingNote: 'Error saving note',
  errorDeletingNote: 'Error deleting note',
  errorActivatingNotes: 'Failed to activate notes. Please try again.',
  errorLoadingStudents: 'Failed to load student data. Please try again.',
  errorSavingStudents: 'Failed to save student data. Please try again.',

  // School & Classes
  loadingClasses: 'Loading classes',
  failedToFetchClasses: 'Failed to fetch classes',
  noClassAssigned: 'No class assigned',

  // Common Actions
  save: 'Save',
  delete: 'Delete',
  edit: 'Edit',
  close: 'Close',
  open: 'Open',
  loadingData: 'Loading data...',
  errorOccurred: 'An error occurred',
  tryAgain: 'Please try again',
  success: 'Success',
  error: 'Error',
  warning: 'Warning',
  info: 'Info',

  // Form Validation
  required: 'Required',
  invalid: 'Invalid',
  tooShort: 'Too short',
  tooLong: 'Too long',
  invalidFormat: 'Invalid format',

  // Time & Date
  today: 'Today',
  yesterday: 'Yesterday',
  tomorrow: 'Tomorrow',
  thisWeek: 'This week',
  thisMonth: 'This month',
  thisYear: 'This year',

  // Status
  active: 'Active',
  inactive: 'Inactive',
  pending: 'Pending',
  completed: 'Completed',
  cancelled: 'Cancelled',
  draft: 'Draft',

  // School Management
  schoolName: 'School Name',
  schoolCode: 'School Code',
  schoolAddress: 'School Address',
  schoolPhone: 'School Phone',
  schoolEmail: 'School Email',
  joinSchool: 'Join School',
  leaveSchool: 'Leave School',
  schoolJoined: 'School joined successfully',
  schoolLeft: 'School left successfully',

  // Student Management
  students: 'Students',
  studentName: 'Student Name',
  studentId: 'Student ID',
  studentClass: 'Student Class',
  addStudent: 'Add Student',
  removeStudent: 'Remove Student',
  studentAdded: 'Student added successfully',
  studentRemoved: 'Student removed successfully',

  // Grade Management
  grades: 'Grades',
  grade: 'Grade',
  average: 'Average',
  highest: 'Highest',
  lowest: 'Lowest',
  pass: 'Pass',
  fail: 'Fail',
  excellent: 'Excellent',
  veryGood: 'Very Good',
  good: 'Good',
  satisfactory: 'Satisfactory',
  needsImprovement: 'Needs Improvement',

  // Attendance
  present: 'Present',
  absent: 'Absent',
  late: 'Late',
  excused: 'Excused',
  attendanceRate: 'Attendance Rate',
  totalDays: 'Total Days',
  presentDays: 'Present Days',
  absentDays: 'Absent Days',

  // Communication
  message: 'Message',
  messages: 'Messages',
  received: 'Received',
  sent: 'Sent',
  reply: 'Reply',
  forward: 'Forward',
  markAsRead: 'Mark as Read',
  markAsUnread: 'Mark as Unread',
  deleteMessage: 'Delete Message',
  messageSent: 'Message sent successfully',
  messageDeleted: 'Message deleted successfully',

  // Settings
  settings: 'Settings',
  preferences: 'Preferences',
  account: 'Account',
  privacy: 'Privacy',
  security: 'Security',
  about: 'About',
  help: 'Help',
  support: 'Support',
  feedback: 'Feedback',
  version: 'Version',
  build: 'Build',

  // Error Messages
  networkError: 'Network error. Please check your connection.',
  serverError: 'Server error. Please try again later.',
  unauthorized: 'Unauthorized access.',
  forbidden: 'Access forbidden.',
  notFound: 'Resource not found.',
  conflict: 'Conflict occurred.',
  timeout: 'Request timeout.',
  unknownError: 'An unknown error occurred.',

  // Success Messages
  operationSuccessful: 'Operation completed successfully.',
  dataSaved: 'Data saved successfully.',
  dataUpdated: 'Data updated successfully.',
  dataDeleted: 'Data deleted successfully.',
  changesSaved: 'Changes saved successfully.',

  // Confirmation Messages
  confirmAction: 'Confirm Action',
  areYouSure: 'Are you sure?',
  thisActionCannotBeUndone: 'This action cannot be undone.',
  confirmDelete: 'Confirm Delete',
  confirmSave: 'Confirm Save',
  confirmCancel: 'Confirm Cancel'
}

export default resource
