import { ILocalization } from "./tr";

const resource: ILocalization = {
  hello: "translated hello",
  name: "Ali Burhan Keskin",
  confirm: "Confirm",
  cancel: "Cancel",
  generalActivityIndicatorText: "Loading...",
  pleaseWait: "Please wait... ",
  generalErrorText: "An error occurred, please try again later.",
  search: "Search",
  noInternet: "No Internet Connection",
  yes: "Yes",
  no: "No",
  exit: "Exit",
  brand: "Brand",
  published: "Published",
  min: "min",
  piece: "Piece",
  time: "Time",
  description: "Description",
  send: "Send",
  next: "Next",
  previous: "Previous",
  retry: "Retry",

  navigation: {
    home: "Home Page",
    profile: "Profile",
    settings: "Settings",
    post: "Post",
  },
  welcome: "Welcome!",
  welcomeBack: "Welcome back!",
  email: "Email",
  password: "Password",
  forgotPassword: "Forgot password?",
  login: "Login",
  or: "or",
  loginWithGoogle: "Login with Google",
  dontHaveAccount: "Don't have an account?",
  register: "Register",
  googleLoginNotImplemented: "Google login is not yet implemented.",
  forgotPasswordNotImplemented:
    "Forgot password functionality is not yet implemented.",
  invalidCredentials: "Invalid email or password",
  createAccount: "Create Account",
  fullName: "Full Name",
  firstName: "First Name",
  lastName: "Last Name",
  phone: "Phone Number",
  invalidPhoneNumber: "This is not a valid ivoirian phone number",
  invalidEmail: "Invalid Email",
  confirmPassword: "Confirm Password",
  passwordsDoNotMatch: "Passwords do not match",
  acceptTerms: "I accept the",
  termsAndConditions: "Terms and Conditions",
  termsAndConditionsNotImplemented:
    "Terms and Conditions are not yet implemented.",
  registrationSuccessful: "Registration successful!",
  back: "Back",
  passwordStrength: {
    weak: "Weak",
    fair: "Fair",
    good: "Good",
    strong: "Strong",
    veryStrong: "Very Strong",
  },
  title: "Profile",
  theme: "Theme",
  system: "System",
  dark: "Dark",
  light: "Light",
  language: "Language",
  fr: "French",
  en: "English",
  tr: "Turkish",
  notifications: "Notifications",
  logout: "Logout",
  attendance: "Attendance",
  notes: "Grades",
  schedule: "Schedule",
  exercises: "Exercises",
  discussion: "Discussion",
  infoAndSchooling: "Info and Schooling",
};

export default resource;
