const resource = {
  hello: "Bonjour traduit",
  name: "Ali Burhan Keskin",
  confirm: "Confirmer",
  cancel: "Annuler",
  generalActivityIndicatorText: "Chargement...",
  pleaseWait: "Veuillez patienter... ",
  generalErrorText: "Une erreur est survenue, veuillez réessayer plus tard.",
  search: "Rechercher",
  noInternet: "Pas de connexion Internet",
  yes: "Oui",
  no: "Non",
  exit: "Quitter",
  brand: "Marque",
  published: "Publié",
  min: "min",
  piece: "Pièce",
  time: "Temps",
  description: "Description",
  send: "Envoyer",
  next: "Suivant",
  previous: "Précédent",
  retry: "Réessayer",

  navigation: {
    home: "Page d'accueil",
    profile: "Profil",
    settings: "Paramètres",
    post: "Publication",
  },
  welcome: "Bienvenue !",
  welcomeBack: "Content de vous revoir !",
  email: "Email",
  password: "Mot de passe",
  forgotPassword: "Mot de passe oublié ?",
  login: "Connexion",
  or: "ou",
  loginWithGoogle: "Continuer avec Google",
  dontHaveAccount: "Vous n'avez pas de compte ?",
  register: "S'inscrire",
  googleLoginNotImplemented:
    "La connexion avec Google n'est pas encore implémentée.",
  forgotPasswordNotImplemented:
    "La fonctionnalité de mot de passe oublié n'est pas encore implémentée.",
  invalidCredentials: "Email ou mot de passe invalide",
  createAccount: "Créer un compte",
  fullName: "Nom complet",
  firstName: "Prénom",
  lastName: "Nom de famille",
  phone: "Numéro de téléphone",
  invalidPhoneNumber: "Ce n'est pas un numéro ivoirien valide",
  invalidEmail: "Email invalide",
  confirmPassword: "Confirmer le mot de passe",
  passwordsDoNotMatch: "Les mots de passe ne correspondent pas",
  acceptTerms: "J'accepte les",
  termsAndConditions: "Conditions générales d'utilisation",
  termsAndConditionsNotImplemented:
    "Les conditions générales d'utilisation ne sont pas encore implémentées.",
  registrationSuccessful: "Inscription réussie !",
  back: "Retour",
  passwordStrength: {
    weak: "Faible",
    fair: "Moyen",
    good: "Bon",
    strong: "Fort",
    veryStrong: "Très Fort",
  },
  title: "Profil",
  theme: "Thème",
  system: "Système",
  dark: "Sombre",
  light: "Clair",
  language: "Langue",
  fr: "Français",
  en: "Anglais",
  tr: "Turc",
  notifications: "Notifications",
  logout: "Déconnexion",
  attendance: "Ponctualité",
  notes: "Notes",
  schedule: "Emploi du temps",
  exercises: "Exercices",
  discussion: "Discussion",
  infoAndSchooling: "Info et scolarité",
};

export default resource;
