// src/localization/tr.ts

const resource = {
  hello: 'translated hello',
  name: 'Ali Burhan Keskin',
  confirm: 'Onayla',
  cancel: 'İptal',
  generalActivityIndicatorText: 'Yükleniyor...',
  pleaseWait: 'Lütfen Bekleyiniz... ',
  generalErrorText: 'Bir hata oluştu lütfen daha sonra tekrar deneyiniz.',
  search: 'Ara',
  noInternet: 'İnternet bağlantısı yok',
  yes: 'Evet',
  no: 'Hayır',
  exit: 'Çıkış',
  brand: 'Marka',
  published: 'Yayında',
  min: 'dk',
  piece: 'Adet',
  time: 'Zaman',
  description: 'Açıklama',
  send: 'Gönder',
  next: 'İleri',
  previous: 'Önceki',
  retry: 'Tekrar Dene',

  navigation: {
    home: 'Ana Sayfa',
    profile: 'Profil',
    settings: 'Ayarlar',
    post: 'Gönderi'
  },
  welcome: 'Hoş geldiniz!',
  welcomeBack: 'Tekrar hoş geldiniz!',
  email: 'E-posta',
  password: 'Şifre',
  forgotPassword: 'Şifrenizi mi unuttunuz?',
  login: 'Giriş Yap',
  or: 'veya',
  loginWithGoogle: 'Google ile Giriş Yap',
  dontHaveAccount: 'Hesabınız yok mu?',
  googleLoginNotImplemented: 'Google girişi henüz uygulanmadı.',
  forgotPasswordNotImplemented: 'Şifremi unuttum işlevi henüz uygulanmadı.',
  invalidCredentials: 'Geçersiz e-posta veya şifre',
  createAccount: 'Hesap Oluştur',
  fullName: 'Ad Soyad',
  firstName: 'Ad',
  lastName: 'Soyad',
  phone: 'Telefon Numarası',
  invalidPhoneNumber: 'Bu geçerli bir ivoirian telefon numarası değil',
  invalidEmail: 'Geçersiz E-posta',
  confirmPassword: 'Şifreyi Onayla',
  passwordsDoNotMatch: 'Şifreler eşleşmiyor',
  acceptTerms: 'Kabul ediyorum', // Consider adding "the" -> "Şartlar ve Koşulları kabul ediyorum"
  termsAndConditions: 'Şartlar ve Koşullar',
  termsAndConditionsNotImplemented: 'Şartlar ve Koşullar henüz uygulanmadı.',
  registrationSuccessful: 'Kayıt başarılı!',
  back: 'Geri',
  passwordStrength: {
    weak: 'Zayıf',
    fair: 'Orta',
    good: 'İyi',
    strong: 'Güçlü',
    veryStrong: 'Çok Güçlü'
  },
  title: 'Profil',
  theme: 'Tema',
  system: 'Sistem',
  dark: 'Koyu',
  light: 'Açık',
  language: 'Dil',
  fr: 'Fransızca',
  en: 'İngilizce',
  tr: 'Türkçe',
  notifications: 'Bildirimler',
  logout: 'Çıkış Yap',
  attendance: 'Devamlılık',
  notes: 'Notlar',
  schedule: 'Ders Programı',
  exercises: 'Alıştırmalar',
  discussion: 'Tartışma',
  infoAndSchooling: 'Bilgi ve Okul',

  // Authentication & Profile
  googleLoginSuccess: 'Google girişi başarılı!',
  googleLoginFailed: 'Google girişi başarısız',
  signUp: 'Kayıt Ol',
  signIn: 'Giriş Yap',
  signInWithGoogle: 'Google ile Giriş Yap',
  signUpWithGoogle: 'Google ile Kayıt Ol',
  alreadyHaveAccount: 'Zaten hesabınız var mı?',
  completeProfile: 'Profilinizi tamamlayın',
  completeProfileSubtitle: 'Lütfen birkaç ek bilgi sağlayın.',
  profileIncomplete: 'Eksik Profil',
  completeProfileToContinue: 'Devam etmek için lütfen profilinizi tamamlayın.',
  fillAllRequiredFields: 'Lütfen tüm zorunlu alanları doldurun.',
  noUserLoggedIn: 'Giriş yapmış kullanıcı yok.',
  profileUpdateError: 'Profil güncellenirken bir hata oluştu.',
  profileCompletedSuccessfully: 'Profil başarıyla tamamlandı!',
  finish: 'Bitir',
  selectYourSchool: 'Okulunuzu seçin',
  phoneNumber: 'Telefon Numarası',
  emailAddress: 'E-posta Adresi',

  joinYekoCommunity:
    'Yeko topluluğuna katılın ve derslerinizi yönetmeye başlayın.',
  googleSignUpSuccess: 'Google kaydı başarılı!',
  googleSignUpFailed: 'Google kaydı başarısız',
  verifyYourEmail: 'E-postanızı doğrulayın',
  confirmationEmailSent: 'Doğrulama e-postası gönderildi',
  clickLinkToActivate:
    'Hesabınızı etkinleştirmek için lütfen e-postadaki bağlantıya tıklayın.',
  backToLogin: 'Girişe dön',

  // Navigation & Tabs
  programs: 'Programlar',
  schools: 'Okullar',
  chats: 'Sohbetler',
  profile: 'Profil',
  classNotes: 'Sınıf Notları',

  // Schedule
  yourSchedule: 'Ders Programınız',
  noClassScheduled: 'Bu gün için ders planlanmamış',
  youAreStillWithoutSchool: 'Hala okul kurumunuz yok!',
  joinSchoolToStart: 'Başlamak için lütfen en az bir okul kurumuna katılın.',
  monday: 'Pazartesi',
  tuesday: 'Salı',
  wednesday: 'Çarşamba',
  thursday: 'Perşembe',
  friday: 'Cuma',
  mon: 'PZT',
  tue: 'SAL',
  wed: 'ÇAR',
  thu: 'PER',
  fri: 'CUM',

  // Chat
  discussions: 'Tartışmalar',
  conversations: 'Konuşmalar',
  unreadMessages: 'Okunmamış Mesajlar',
  all: 'Tümü',
  unread: 'Okunmamış',
  noUnreadMessages: 'Okunmamış mesaj yok',
  noConversationsFound: 'Konuşma bulunamadı',
  messageLimitReached: 'Limit Aşıldı',
  maxMessagesPerChat:
    'Sohbet başına maksimum mesaj sayısına ulaştınız (10 max).',
  goBack: 'Geri dön',
  sendMessage: 'Mesaj gönder',
  noClass: 'Sınıf yok',
  noSchool: 'Okul yok',

  // Profile & Settings
  updateProfile: 'Profili güncelle',
  modifyNameAndPhoto: 'Adınızı ve fotoğrafınızı değiştirin',
  joinNewSchool: 'Yeni bir okula katıl',
  enterOtpToLink: 'Profilinizi yeni bir okula bağlamak için OTP kodunu girin',
  problemDuringLogout: 'Çıkış sırasında bir sorun yaşandı, tekrar deneyin',
  willBeAvailableSoon: 'Çok yakında kullanılabilir olacak',

  // Notes & Evaluation
  newEvaluation: 'Yeni Değerlendirme',
  loading: 'Yükleniyor...',
  loadingSemesterData: 'Dönem verileri yükleniyor...',
  semester: 'Dönem',
  trimester: 'Üç Aylık Dönem',
  subject: 'Ders',
  evaluationType: 'Değerlendirme Türü',
  evaluationTitle: 'Değerlendirme Başlığı',
  evaluationDescription: 'Değerlendirme Açıklaması',
  totalPoints: 'Toplam Puan',
  coefficient: 'Katsayı',
  dueDate: 'Son Tarih',
  gradeEvaluation: 'Değerlendirmeyi notla',
  create: 'Oluştur',
  creating: 'Oluşturuluyor...',
  titleRequired: 'Başlık gerekli',
  totalPointsMustBePositive: 'Toplam puanlar pozitif bir sayı olmalı',
  coefficientMustBePositive: 'Katsayı pozitif bir sayı olmalı',
  subjectRequired: 'Ders gerekli',
  invalidSubject: 'Geçersiz ders',
  invalidSemester: 'Geçersiz dönem',
  invalidDate: 'Geçersiz tarih',
  notTeacherOfThisClass: 'Bu sınıfın öğretmeni değilsiniz',
  noteNotFound: 'Not bulunamadı',
  errorSavingNote: 'Not kaydedilirken hata',
  errorDeletingNote: 'Not silinirken hata',
  errorActivatingNotes: 'Notlar etkinleştirilemedi. Lütfen tekrar deneyin.',
  errorLoadingStudents: 'Öğrenci verileri yüklenemedi. Lütfen tekrar deneyin.',
  errorSavingStudents: 'Öğrenci verileri kaydedilemedi. Lütfen tekrar deneyin.',

  // School & Classes
  loadingClasses: 'Sınıflar yükleniyor',
  failedToFetchClasses: 'Sınıflar alınamadı',
  noClassAssigned: 'Atanmış sınıf yok',

  // Common Actions
  save: 'Kaydet',
  delete: 'Sil',
  edit: 'Düzenle',
  close: 'Kapat',
  open: 'Aç',
  loadingData: 'Veriler yükleniyor...',
  errorOccurred: 'Bir hata oluştu',
  tryAgain: 'Lütfen tekrar deneyin',
  success: 'Başarılı',
  error: 'Hata',
  warning: 'Uyarı',
  info: 'Bilgi',

  // Form Validation
  required: 'Gerekli',
  invalid: 'Geçersiz',
  tooShort: 'Çok kısa',
  tooLong: 'Çok uzun',
  invalidFormat: 'Geçersiz format',

  // Time & Date
  today: 'Bugün',
  yesterday: 'Dün',
  tomorrow: 'Yarın',
  thisWeek: 'Bu hafta',
  thisMonth: 'Bu ay',
  thisYear: 'Bu yıl',

  // Status
  active: 'Aktif',
  inactive: 'Pasif',
  pending: 'Beklemede',
  completed: 'Tamamlandı',
  cancelled: 'İptal edildi',
  draft: 'Taslak',

  // School Management
  schoolName: 'Okul Adı',
  schoolCode: 'Okul Kodu',
  schoolAddress: 'Okul Adresi',
  schoolPhone: 'Okul Telefonu',
  schoolEmail: 'Okul E-postası',
  joinSchool: 'Okula Katıl',
  leaveSchool: 'Okuldan Ayrıl',
  schoolJoined: 'Okula başarıyla katıldı',
  schoolLeft: 'Okuldan başarıyla ayrıldı',

  // Student Management
  students: 'Öğrenciler',
  studentName: 'Öğrenci Adı',
  studentId: 'Öğrenci ID',
  studentClass: 'Öğrenci Sınıfı',
  addStudent: 'Öğrenci Ekle',
  removeStudent: 'Öğrenciyi Kaldır',
  studentAdded: 'Öğrenci başarıyla eklendi',
  studentRemoved: 'Öğrenci başarıyla kaldırıldı',

  // Grade Management
  grades: 'Notlar',
  grade: 'Not',
  average: 'Ortalama',
  highest: 'En Yüksek',
  lowest: 'En Düşük',
  pass: 'Geçti',
  fail: 'Kaldı',
  excellent: 'Mükemmel',
  veryGood: 'Çok İyi',
  good: 'İyi',
  satisfactory: 'Yeterli',
  needsImprovement: 'Geliştirilmeli',

  // Attendance
  present: 'Mevcut',
  absent: 'Yok',
  late: 'Geç',
  excused: 'Mazeretli',
  attendanceRate: 'Devam Oranı',
  totalDays: 'Toplam Günler',
  presentDays: 'Mevcut Günler',
  absentDays: 'Yok Günler',

  // Communication
  message: 'Mesaj',
  messages: 'Mesajlar',
  received: 'Alındı',
  sent: 'Gönderildi',
  reply: 'Yanıtla',
  forward: 'İlet',
  markAsRead: 'Okundu Olarak İşaretle',
  markAsUnread: 'Okunmadı Olarak İşaretle',
  deleteMessage: 'Mesajı Sil',
  messageSent: 'Mesaj başarıyla gönderildi',
  messageDeleted: 'Mesaj başarıyla silindi',

  // Settings
  settings: 'Ayarlar',
  preferences: 'Tercihler',
  account: 'Hesap',
  privacy: 'Gizlilik',
  security: 'Güvenlik',
  about: 'Hakkında',
  help: 'Yardım',
  support: 'Destek',
  feedback: 'Geri Bildirim',
  version: 'Sürüm',
  build: 'Build',

  // Error Messages
  networkError: 'Ağ hatası. Lütfen bağlantınızı kontrol edin.',
  serverError: 'Sunucu hatası. Lütfen daha sonra tekrar deneyin.',
  unauthorized: 'Yetkisiz erişim.',
  forbidden: 'Erişim yasak.',
  notFound: 'Kaynak bulunamadı.',
  conflict: 'Çakışma oluştu.',
  timeout: 'İstek zaman aşımına uğradı.',
  unknownError: 'Bilinmeyen bir hata oluştu.',

  // Success Messages
  operationSuccessful: 'İşlem başarıyla tamamlandı.',
  dataSaved: 'Veriler başarıyla kaydedildi.',
  dataUpdated: 'Veriler başarıyla güncellendi.',
  dataDeleted: 'Veriler başarıyla silindi.',
  changesSaved: 'Değişiklikler başarıyla kaydedildi.',

  // Confirmation Messages
  confirmAction: 'Eylemi Onayla',
  areYouSure: 'Emin misiniz?',
  thisActionCannotBeUndone: 'Bu eylem geri alınamaz.',
  confirmDelete: 'Silme İşlemini Onayla',
  confirmSave: 'Kaydetme İşlemini Onayla',
  confirmCancel: 'İptal İşlemini Onayla'
}

export default resource

export type ILocalization = typeof resource
